apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ai-loan-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root123"
        - name: MYSQL_DATABASE
          value: "ai_loan_platform"
        - name: MYSQL_USER
          value: "ai_loan"
        - name: MYSQL_PASSWORD
          value: "ai_loan123"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init
        configMap:
          name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ai-loan-platform
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ai-loan-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: ai-loan-platform
data:
  init.sql: |
    -- 数据库初始化脚本
    CREATE DATABASE IF NOT EXISTS ai_loan_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    USE ai_loan_platform;
    -- 这里可以添加更多的初始化SQL
